name: range_type
description: The convenient pure Dart library of ranges representation. Range types are data types representing a range of values of some element type.
version: 0.0.2
repository: https://github.com/cyrax111/range_type

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
